Repository apcountryman/prototype-kicad-library-ci, pull requests merged in 2021-06, with the labels that each got.

#14 Add KiCad project file scrub
  .gitattributes
  .github/workflows/ci.yml
  README.md
  ci/scrub-kicad-project-files
  git/config/install
  test/test.pro
Labels: priority-normal, status-in_review, type-feature

#16 Add KiCad footprint cache Git ignore rule
  .gitignore
Labels: priority-normal, status-in_review, type-enhancement

#18 Move test library to repository root
  fp-lib-table
  sym-lib-table
  test.dcm
  test.lib
  test.pretty/10_uMAX.kicad_mod
  test.pro
Labels: priority-normal, status-in_review, type-refactoring
